FROM debian:bullseye-slim

# Install wget, lsb-release and curl
RUN apt update && apt install -y wget gnupg2 gettext-base

# Add key
#RUN wget -O - http://ppa.moosefs.com/moosefs.key 2>/dev/null | apt-key add - 2>/dev/null
RUN wget -O - https://ppa.moosefs.com/moosefs.key | apt-key add -
RUN echo "deb [arch=amd64] http://ppa.moosefs.com/moosefs-3/apt/debian/bullseye bullseye main" > /etc/apt/sources.list.d/moosefs.list

# Install MooseFS chunkserver
RUN apt update && apt install -y moosefs-chunkserver

# Expose ports
EXPOSE 9422

# Add start script
ADD chunkserver.sh /usr/sbin/chunkserver.sh
RUN chown root:root /usr/sbin/chunkserver.sh ; chmod 700 /usr/sbin/chunkserver.sh

CMD ["chunkserver.sh"]
