FROM ubuntu:jammy

# Install wget and gnupg2
RUN apt update && apt install -y wget gnupg2 gettext-base

# Add key
#RUN wget -O - http://ppa.moosefs.com/moosefs.key 2>/dev/null | apt-key add - 2>/dev/null
RUN wget -O - https://ppa.moosefs.com/moosefs.key | apt-key add -
RUN echo "deb [arch=arm64] http://ppa.moosefs.com/moosefs-3/apt/ubuntu/jammy jammy main" > /etc/apt/sources.list.d/moosefs.list

# Install MooseFS metalogger
RUN apt update && apt install -y moosefs-metalogger

# Add and run start script
ADD metalogger.sh /usr/sbin/metalogger.sh
RUN chown root:root /usr/sbin/metalogger.sh ; chmod 700 /usr/sbin/metalogger.sh

CMD ["metalogger.sh"]
